// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// All secrets live in .env.local (Prisma CLI doesn't read it automatically, so load it explicitly).
dotenv.config({ path: ".env.local" });

export default defineConfig({
  // MongoDB uses `prisma db push`, not SQL migrations — no migrations path.
  schema: "prisma/schema.prisma",
  datasource: {
    url: process.env["DATABASE_URL"] ?? "",
  },
});
